// <auto-generated />
using System;
using DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAO.Migrations
{
    [DbContext(typeof(dbContextINA))]
    [Migration("20250925182658_inicialeshkldfjaw")]
    partial class inicialeshkldfjaw
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.Property<int>("idActivo")
                        .HasColumnType("int");

                    b.Property<int>("cantidadDisponible")
                        .HasColumnType("int")
                        .HasColumnName("CantidadDisponible");

                    b.Property<int?>("clsDonacionidDonacion")
                        .HasColumnType("int");

                    b.Property<decimal>("costoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("fechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("fechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<string>("nombreActivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("proveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idActivo");

                    b.HasIndex("clsDonacionidDonacion");

                    b.HasIndex("idCategoria");

                    b.ToTable("tbActivos");
                });

            modelBuilder.Entity("Entities.clsCategoriaActivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tbCategoriaActivos");
                });

            modelBuilder.Entity("Entities.clsDepartamentos", b =>
                {
                    b.Property<int>("idDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDepartamento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("codigoDepartamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("descripcionDepartamento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("fecha_ult_mod")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("usuario_crea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("usuario_ult_mod")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("idDepartamento");

                    b.ToTable("tbDepartamento");
                });

            modelBuilder.Entity("Entities.clsDevolucion", b =>
                {
                    b.Property<int>("idDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDevolucion"));

                    b.Property<DateTime>("fechaDevolucion")
                        .HasColumnType("date");

                    b.Property<int>("idActivoFK")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idDevolucion");

                    b.HasIndex("idActivoFK");

                    b.ToTable("tbDevolucion");
                });

            modelBuilder.Entity("Entities.clsDonacion", b =>
                {
                    b.Property<int>("idDonacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonacion"));

                    b.Property<string>("donanteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("donantepersonaId");

                    b.Property<int>("donanteTipoId")
                        .HasColumnType("int")
                        .HasColumnName("donanteTipoId");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaDonacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaProximaDonacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("frecuencia")
                        .HasColumnType("int");

                    b.Property<int>("idTipoDonacion")
                        .HasColumnType("int");

                    b.Property<decimal?>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("razonInactivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("razonModifica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("tipoMoneda")
                        .HasColumnType("int");

                    b.Property<int?>("tipoTransaccion")
                        .HasColumnType("int");

                    b.Property<string>("usuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idDonacion");

                    b.HasIndex("idTipoDonacion");

                    b.HasIndex("donanteId", "donanteTipoId");

                    b.ToTable("tbDonacion", (string)null);
                });

            modelBuilder.Entity("Entities.clsDonante", b =>
                {
                    b.Property<string>("personaId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("personaTipoId")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("razonInactivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("razonModifica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("tipoDonante")
                        .HasColumnType("int");

                    b.Property<string>("usuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("personaId", "personaTipoId");

                    b.ToTable("tbDonante", (string)null);
                });

            modelBuilder.Entity("Entities.clsEnfermero", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<int>("tipoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("area")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaUltMod")
                        .HasColumnType("datetime2");

                    b.Property<string>("numeroColegiado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("usuarioCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioUltMod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id", "tipoId");

                    b.ToTable("tbEnfermeros");
                });

            modelBuilder.Entity("Entities.clsEspecialidadMedica", b =>
                {
                    b.Property<int>("idEspecialidadMedica")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idEspecialidadMedica");

                    b.ToTable("tbEspecialidadMedica");
                });

            modelBuilder.Entity("Entities.clsMedico", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("tipoId")
                        .HasColumnType("int");

                    b.Property<string>("especialidad")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaUltMod")
                        .HasColumnType("datetime2");

                    b.Property<int>("idPersona")
                        .HasColumnType("int");

                    b.Property<string>("usuarioCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioUltMod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id", "tipoId");

                    b.ToTable("tbMedico");
                });

            modelBuilder.Entity("Entities.clsModulo", b =>
                {
                    b.Property<int>("id_modulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_modulo"));

                    b.Property<string>("descripcion_modulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nombre_modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_modulo");

                    b.ToTable("tb_Modulo");
                });

            modelBuilder.Entity("Entities.clsPaciente", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("tipoId")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("estadoCivil")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_ult_mod")
                        .HasColumnType("datetime2");

                    b.Property<string>("usuario_crea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuario_ult_mod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id", "tipoId");

                    b.ToTable("tbPaciente");
                });

            modelBuilder.Entity("Entities.clsPermisos", b =>
                {
                    b.Property<int>("idPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPermiso"));

                    b.Property<int?>("clsModuloid_modulo")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idPermiso");

                    b.HasIndex("clsModuloid_modulo");

                    b.ToTable("tbPermisos");
                });

            modelBuilder.Entity("Entities.clsPersona", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("tipoId")
                        .HasColumnType("int");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("apellido2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id", "tipoId");

                    b.ToTable("tbPersonas");
                });

            modelBuilder.Entity("Entities.clsPuestos", b =>
                {
                    b.Property<int>("idPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPuesto"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("fecha_ult_mod")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("idDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("motivoInactivo")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR(300)");

                    b.Property<string>("usuario_crea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("usuario_ult_mod")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("idPuesto");

                    b.HasIndex("idDepartamento");

                    b.ToTable("tbPuestos");
                });

            modelBuilder.Entity("Entities.clsRol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRol"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreRol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idRol");

                    b.ToTable("tbRoles");
                });

            modelBuilder.Entity("Entities.clsRolPermiso", b =>
                {
                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<int>("idPermiso")
                        .HasColumnType("int");

                    b.Property<int>("PermisoidPermiso")
                        .HasColumnType("int");

                    b.Property<int>("RolidRol")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("idRol", "idPermiso");

                    b.HasIndex("PermisoidPermiso");

                    b.HasIndex("RolidRol");

                    b.ToTable("tbRolPermiso");
                });

            modelBuilder.Entity("Entities.clsTipoDonacion", b =>
                {
                    b.Property<int>("idTipoDonacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoDonacion"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreTipoDonacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("razonInactivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("razonModifica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("requiereFrecuencia")
                        .HasColumnType("bit");

                    b.Property<bool>("requiereMonto")
                        .HasColumnType("bit");

                    b.Property<bool>("requiereTipoMoneda")
                        .HasColumnType("bit");

                    b.Property<bool>("requiereTipoTransaccion")
                        .HasColumnType("bit");

                    b.Property<string>("usuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoDonacion");

                    b.ToTable("tbTipoDonacion", (string)null);
                });

            modelBuilder.Entity("Entities.clsUsuario", b =>
                {
                    b.Property<string>("personaId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("personaTipoId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personaId", "personaTipoId");

                    b.ToTable("tbUsuarios");
                });

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.HasOne("Entities.clsDonacion", null)
                        .WithMany("activos")
                        .HasForeignKey("clsDonacionidDonacion");

                    b.HasOne("Entities.clsCategoriaActivos", "categoria")
                        .WithMany("Activos")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("Entities.clsDevolucion", b =>
                {
                    b.HasOne("Entities.clsActivos", "activo")
                        .WithMany("devoluciones")
                        .HasForeignKey("idActivoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("activo");
                });

            modelBuilder.Entity("Entities.clsDonacion", b =>
                {
                    b.HasOne("Entities.clsTipoDonacion", "tipoDonacion")
                        .WithMany("donaciones")
                        .HasForeignKey("idTipoDonacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.clsDonante", "donante")
                        .WithMany()
                        .HasForeignKey("donanteId", "donanteTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("donante");

                    b.Navigation("tipoDonacion");
                });

            modelBuilder.Entity("Entities.clsDonante", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne("donante")
                        .HasForeignKey("Entities.clsDonante", "personaId", "personaTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsEnfermero", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithMany()
                        .HasForeignKey("id", "tipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsMedico", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne()
                        .HasForeignKey("Entities.clsMedico", "id", "tipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsPaciente", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne("paciente")
                        .HasForeignKey("Entities.clsPaciente", "id", "tipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsPermisos", b =>
                {
                    b.HasOne("Entities.clsModulo", null)
                        .WithMany("permisos")
                        .HasForeignKey("clsModuloid_modulo");
                });

            modelBuilder.Entity("Entities.clsPuestos", b =>
                {
                    b.HasOne("Entities.clsDepartamentos", "Departamento")
                        .WithMany("Puestos")
                        .HasForeignKey("idDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Entities.clsRolPermiso", b =>
                {
                    b.HasOne("Entities.clsPermisos", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoidPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.clsRol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolidRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Entities.clsUsuario", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne()
                        .HasForeignKey("Entities.clsUsuario", "personaId", "personaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.Navigation("devoluciones");
                });

            modelBuilder.Entity("Entities.clsCategoriaActivos", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("Entities.clsDepartamentos", b =>
                {
                    b.Navigation("Puestos");
                });

            modelBuilder.Entity("Entities.clsDonacion", b =>
                {
                    b.Navigation("activos");
                });

            modelBuilder.Entity("Entities.clsModulo", b =>
                {
                    b.Navigation("permisos");
                });

            modelBuilder.Entity("Entities.clsPermisos", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Entities.clsPersona", b =>
                {
                    b.Navigation("donante")
                        .IsRequired();

                    b.Navigation("paciente")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.clsRol", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Entities.clsTipoDonacion", b =>
                {
                    b.Navigation("donaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
