// <auto-generated />
using System;
using DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAO.Migrations
{
    [DbContext(typeof(dbContextINA))]
    partial class dbContextINAModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.Property<int>("idActivo")
                        .HasColumnType("int");

                    b.Property<int>("cantidadDisponible")
                        .HasColumnType("int")
                        .HasColumnName("CantidadDisponible");

                    b.Property<decimal>("costoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("fechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("fechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<string>("nombreActivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("proveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idActivo");

                    b.HasIndex("idCategoria");

                    b.ToTable("tbActivos");
                });

            modelBuilder.Entity("Entities.clsCategoriaActivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tbCategoriaActivos");
                });

            modelBuilder.Entity("Entities.clsDepartamentos", b =>
                {
                    b.Property<int>("idDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDepartamento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("codigoDepartamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("descripcionDepartamento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("fecha_ult_mod")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("usuario_crea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("usuario_ult_mod")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("idDepartamento");

                    b.ToTable("tbDepartamento");
                });

            modelBuilder.Entity("Entities.clsDevolucion", b =>
                {
                    b.Property<int>("idDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDevolucion"));

                    b.Property<DateTime>("fechaDevolucion")
                        .HasColumnType("date");

                    b.Property<int>("idActivoFK")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idDevolucion");

                    b.HasIndex("idActivoFK");

                    b.ToTable("tbDevolucion");
                });

            modelBuilder.Entity("Entities.clsEspecialidadMedica", b =>
                {
                    b.Property<int>("idEspecialidadMedica")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idEspecialidadMedica");

                    b.ToTable("tbEspecialidadMedica");
                });

            modelBuilder.Entity("Entities.clsMedico", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("tipoId")
                        .HasColumnType("int");

                    b.Property<string>("especialidad")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaUltMod")
                        .HasColumnType("datetime2");

                    b.Property<int>("idPersona")
                        .HasColumnType("int");

                    b.Property<string>("usuarioCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioUltMod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id", "tipoId");

                    b.ToTable("tbMedico");
                });

            modelBuilder.Entity("Entities.clsPaciente", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("estadoCivil")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_ult_mod")
                        .HasColumnType("datetime2");

                    b.Property<int>("tipoId")
                        .HasColumnType("int");

                    b.Property<string>("usuario_crea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuario_ult_mod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("id", "tipoId")
                        .IsUnique();

                    b.ToTable("tbPaciente");
                });

            modelBuilder.Entity("Entities.clsPermisos", b =>
                {
                    b.Property<int>("idPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPermiso"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idPermiso");

                    b.ToTable("tbPermisos");
                });

            modelBuilder.Entity("Entities.clsPersona", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("tipoId")
                        .HasColumnType("int");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("apellido2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id", "tipoId");

                    b.ToTable("tbPersonas");
                });

            modelBuilder.Entity("Entities.clsPuestos", b =>
                {
                    b.Property<int>("idPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPuesto"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("fecha_ult_mod")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("idDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("motivoInactivo")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR(300)");

                    b.Property<string>("usuario_crea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("usuario_ult_mod")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("idPuesto");

                    b.HasIndex("idDepartamento");

                    b.ToTable("tbPuestos");
                });

            modelBuilder.Entity("Entities.clsRol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRol"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreRol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idRol");

                    b.ToTable("tbRoles");
                });

            modelBuilder.Entity("Entities.clsRolPermiso", b =>
                {
                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<int>("idPermiso")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("idRol", "idPermiso");

                    b.HasIndex("idPermiso");

                    b.ToTable("tbRolPermiso");
                });

            modelBuilder.Entity("Entities.clsTiposAyudas", b =>
                {
                    b.Property<int>("id_tipoAyuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipoAyuda"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_ultimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_responsable")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("id_usuarioCrea")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("id_usuarioUltimaModificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("personaTipoId_responsable")
                        .HasColumnType("int");

                    b.Property<int>("personaTipoId_usuarioCrea")
                        .HasColumnType("int");

                    b.Property<int>("personaTipoId_usuarioUltimaModificacion")
                        .HasColumnType("int");

                    b.HasKey("id_tipoAyuda");

                    b.ToTable("tb_tipoAyuda");
                });

            modelBuilder.Entity("Entities.clsUsuario", b =>
                {
                    b.Property<string>("personaId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("personaTipoId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personaId", "personaTipoId");

                    b.ToTable("tbUsuarios");
                });

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.HasOne("Entities.clsCategoriaActivos", "categoria")
                        .WithMany("Activos")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("Entities.clsDevolucion", b =>
                {
                    b.HasOne("Entities.clsActivos", "activo")
                        .WithMany("devoluciones")
                        .HasForeignKey("idActivoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("activo");
                });

            modelBuilder.Entity("Entities.clsMedico", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne()
                        .HasForeignKey("Entities.clsMedico", "id", "tipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsPaciente", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne("paciente")
                        .HasForeignKey("Entities.clsPaciente", "id", "tipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsPuestos", b =>
                {
                    b.HasOne("Entities.clsDepartamentos", "Departamento")
                        .WithMany("Puestos")
                        .HasForeignKey("idDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Entities.clsRolPermiso", b =>
                {
                    b.HasOne("Entities.clsPermisos", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("idPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.clsRol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Entities.clsUsuario", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithMany()
                        .HasForeignKey("personaId", "personaTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.Navigation("devoluciones");
                });

            modelBuilder.Entity("Entities.clsCategoriaActivos", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("Entities.clsDepartamentos", b =>
                {
                    b.Navigation("Puestos");
                });

            modelBuilder.Entity("Entities.clsPermisos", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Entities.clsPersona", b =>
                {
                    b.Navigation("paciente")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.clsRol", b =>
                {
                    b.Navigation("RolPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
