// <auto-generated />
using System;
using DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAO.Migrations
{
    [DbContext(typeof(dbContextINA))]
    partial class dbContextINAModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.Property<int>("idActivo")
                        .HasColumnType("int");

                    b.Property<int>("cantidadDisponible")
                        .HasColumnType("int")
                        .HasColumnName("CantidadDisponible");

                    b.Property<decimal>("costoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("fechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("fechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<string>("nombreActivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("proveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idActivo");

                    b.HasIndex("idCategoria");

                    b.ToTable("tbActivos");
                });

            modelBuilder.Entity("Entities.clsCategoriaActivos", b =>
                {
                    b.Property<int>("idCategoriaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCategoriaActivo"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreCategoriaActivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idCategoriaActivo");

                    b.ToTable("tbCategoriaActivos");
                });

            modelBuilder.Entity("Entities.clsDepartamentos", b =>
                {
                    b.Property<int>("idDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDepartamento"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioModificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDepartamento");

                    b.ToTable("tbDepartamento");
                });

            modelBuilder.Entity("Entities.clsDevolucion", b =>
                {
                    b.Property<int>("idDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDevolucion"));

                    b.Property<DateTime>("fechaDevolucion")
                        .HasColumnType("date");

                    b.Property<int>("idActivoFK")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idDevolucion");

                    b.HasIndex("idActivoFK");

                    b.ToTable("tbDevolucion");
                });

            modelBuilder.Entity("Entities.clsDonacion", b =>
                {
                    b.Property<int>("idDonacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonacion"));

<<<<<<< HEAD
                    b.Property<DateTime>("fechaDonacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idDonante")
                        .HasColumnType("int");

=======
                    b.Property<string>("donantepersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("donantepersonaTipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaDonacion")
                        .HasColumnType("datetime2");

>>>>>>> 9d6a69bbe7f4c857b2c996c148975be9f4596cb0
                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipoDonacion")
                        .HasColumnType("int");

                    b.HasKey("idDonacion");

<<<<<<< HEAD
                    b.HasIndex("idDonante");
=======
                    b.HasIndex("donantepersonaId", "donantepersonaTipoId");
>>>>>>> 9d6a69bbe7f4c857b2c996c148975be9f4596cb0

                    b.ToTable("tbDonaciones");
                });

<<<<<<< HEAD
            modelBuilder.Entity("Entities.clsDonacionActivo", b =>
                {
                    b.Property<int>("IdDonacionActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonacionActivo"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("EstadoActivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdDonacion")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("clsActivosIdActivo")
                        .HasColumnType("int");

                    b.HasKey("IdDonacionActivo");

                    b.HasIndex("IdDonacion");

                    b.HasIndex("clsActivosIdActivo");

                    b.ToTable("tbDonacionesActivos");
                });

=======
>>>>>>> develop
            modelBuilder.Entity("Entities.clsDonacionDinero", b =>
                {
                    b.Property<int>("idDonacionDinero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonacionDinero"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("frecuencia")
                        .HasColumnType("int");

                    b.Property<int>("idDonacion")
                        .HasColumnType("int");

                    b.Property<string>("moneda")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tipoTransaccion")
                        .HasColumnType("int");

                    b.HasKey("idDonacionDinero");

                    b.HasIndex("idDonacion")
                        .IsUnique();

                    b.ToTable("tbDonacionesDinero");
                });

            modelBuilder.Entity("Entities.clsDonacionesActivos", b =>
                {
                    b.Property<int>("idDonacionActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonacionActivo"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("estadoActivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("idActivo")
                        .HasColumnType("int");

                    b.Property<int>("idDonacion")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDonacionActivo");

                    b.HasIndex("idActivo");

                    b.HasIndex("idDonacion");

                    b.ToTable("tbDonacionesActivos");
                });

            modelBuilder.Entity("Entities.clsDonante", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("idDonante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonante"));

=======
                    b.Property<string>("personaId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("personaTipoId")
                        .HasColumnType("int");

>>>>>>> 9d6a69bbe7f4c857b2c996c148975be9f4596cb0
                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime2");

<<<<<<< HEAD
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");
=======
<<<<<<< HEAD
                    b.Property<string>("personaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");
>>>>>>> develop

                    b.Property<int>("personaTipoId")
                        .HasColumnType("int");

                    b.HasKey("idDonante");

                    b.HasIndex("personaId", "personaTipoId")
                        .IsUnique();
=======
                    b.HasKey("personaId", "personaTipoId");
>>>>>>> 9d6a69bbe7f4c857b2c996c148975be9f4596cb0

                    b.ToTable("tbDonantes");
                });

            modelBuilder.Entity("Entities.clsEnfermero", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<int>("tipoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("area")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

<<<<<<< HEAD
                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("PersonaTipoId")
                        .HasColumnType("int");

                    b.Property<int>("Personaid")
                        .HasColumnType("int");

=======
>>>>>>> develop
                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaUltMod")
                        .HasColumnType("datetime2");

                    b.Property<string>("numeroColegiado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("usuarioCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioUltMod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id", "tipoId");

<<<<<<< HEAD
                    b.HasIndex("Personaid", "PersonaTipoId");

                    b.ToTable("tbEnfermero");
=======
                    b.ToTable("tbEnfermeros");
>>>>>>> develop
                });

            modelBuilder.Entity("Entities.clsEspecialidadMedica", b =>
                {
                    b.Property<int>("idEspecialidadMedica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEspecialidadMedica"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idEspecialidadMedica");

                    b.ToTable("tbEspecialidadMedica");
                });

            modelBuilder.Entity("Entities.clsMedico", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("tipoId")
                        .HasColumnType("int");

                    b.Property<string>("especialidad")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaUltMod")
                        .HasColumnType("datetime2");

                    b.Property<int>("idPersona")
                        .HasColumnType("int");

                    b.Property<string>("usuarioCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("usuarioUltMod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id", "tipoId");

                    b.ToTable("tbMedico");
                });

            modelBuilder.Entity("Entities.clsModulo", b =>
                {
                    b.Property<int>("id_modulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_modulo"));

                    b.Property<string>("descripcion_modulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nombre_modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_modulo");

                    b.ToTable("tb_Modulo");
                });

            modelBuilder.Entity("Entities.clsPermisos", b =>
                {
                    b.Property<int>("idPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPermiso"));

                    b.Property<int?>("clsModuloid_modulo")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idPermiso");

                    b.HasIndex("clsModuloid_modulo");

                    b.ToTable("tbPermisos");
                });

            modelBuilder.Entity("Entities.clsPersona", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("PersonaTipoId")
                        .HasColumnType("int");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("apellido2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id", "PersonaTipoId");

                    b.ToTable("tbPersonas");
                });

            modelBuilder.Entity("Entities.clsPuestos", b =>
                {
                    b.Property<int>("idPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPuesto"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombrePuesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idPuesto");

                    b.ToTable("tbPuestos");
                });

<<<<<<< HEAD
            modelBuilder.Entity("Entities.clsTiposAyudas", b =>
                {
                    b.Property<int>("id_tipoAyuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipoAyuda"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");
=======
            modelBuilder.Entity("Entities.clsRol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRol"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
>>>>>>> develop

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

<<<<<<< HEAD
                    b.Property<DateTime>("fecha_crea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_ultimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_responsable")
                        .HasColumnType("int");

                    b.Property<int>("id_usuarioCrea")
                        .HasColumnType("int");

                    b.Property<int>("id_usuarioUltimaModificacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
=======
                    b.Property<string>("nombreRol")
>>>>>>> develop
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

<<<<<<< HEAD
                    b.HasKey("id_tipoAyuda");

                    b.HasIndex("id_responsable");

                    b.HasIndex("id_usuarioCrea");

                    b.HasIndex("id_usuarioUltimaModificacion");

                    b.ToTable("tb_tipoAyuda");
=======
                    b.HasKey("idRol");

                    b.ToTable("tbRoles");
                });

            modelBuilder.Entity("Entities.clsRolPermiso", b =>
                {
                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<int>("idPermiso")
                        .HasColumnType("int");

                    b.Property<int>("PermisoidPermiso")
                        .HasColumnType("int");

                    b.Property<int>("RolidRol")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("idRol", "idPermiso");

                    b.HasIndex("PermisoidPermiso");

                    b.HasIndex("RolidRol");

                    b.ToTable("tbRolPermiso");
>>>>>>> develop
                });

            modelBuilder.Entity("Entities.clsUsuario", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaTipoId")
                        .HasColumnType("int");

                    b.Property<string>("contraseña")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("rol_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PersonaId", "PersonaTipoId");

                    b.ToTable("usuarios");
=======
                    b.Property<string>("personaId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("personaTipoId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personaId", "personaTipoId");

                    b.ToTable("tbUsuarios");
>>>>>>> develop
                });

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.HasOne("Entities.clsCategoriaActivos", "categoria")
                        .WithMany()
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("Entities.clsDevolucion", b =>
                {
                    b.HasOne("Entities.clsActivos", "activo")
                        .WithMany("devoluciones")
                        .HasForeignKey("idActivoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("activo");
                });

            modelBuilder.Entity("Entities.clsDonacion", b =>
                {
                    b.HasOne("Entities.clsDonante", "donante")
                        .WithMany("donaciones")
<<<<<<< HEAD
                        .HasForeignKey("idDonante")
=======
                        .HasForeignKey("donantepersonaId", "donantepersonaTipoId")
>>>>>>> 9d6a69bbe7f4c857b2c996c148975be9f4596cb0
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<< HEAD
                    b.Navigation("Donante");
                });

            modelBuilder.Entity("Entities.clsDonacionActivo", b =>
                {
                    b.HasOne("Entities.clsDonacion", "Donacion")
                        .WithMany("DonacionActivos")
                        .HasForeignKey("IdDonacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.clsActivos", null)
                        .WithMany("DonacionActivos")
                        .HasForeignKey("clsActivosIdActivo");

                    b.Navigation("Donacion");
=======
                    b.Navigation("donante");
>>>>>>> develop
                });

            modelBuilder.Entity("Entities.clsDonacionDinero", b =>
                {
                    b.HasOne("Entities.clsDonacion", "donacion")
                        .WithOne("donacionDinero")
                        .HasForeignKey("Entities.clsDonacionDinero", "idDonacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("donacion");
                });

            modelBuilder.Entity("Entities.clsDonacionesActivos", b =>
                {
                    b.HasOne("Entities.clsActivos", "activo")
                        .WithMany("donacionActivos")
                        .HasForeignKey("idActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.clsDonacion", "donacion")
                        .WithMany("donacionesActivos")
                        .HasForeignKey("idDonacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("activo");

                    b.Navigation("donacion");
                });

            modelBuilder.Entity("Entities.clsDonante", b =>
                {
<<<<<<< HEAD
                    b.HasOne("Entities.clsPersona", "Persona")
                        .WithOne("Donante")
                        .HasForeignKey("Entities.clsDonante", "PersonaId", "PersonaTipoId")
=======
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne("donante")
                        .HasForeignKey("Entities.clsDonante", "personaId", "personaTipoId")
>>>>>>> develop
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsEnfermero", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithMany()
<<<<<<< HEAD
                        .HasForeignKey("Personaid", "PersonaTipoId")
=======
                        .HasForeignKey("id", "tipoId")
>>>>>>> develop
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsMedico", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne()
                        .HasForeignKey("Entities.clsMedico", "id", "tipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsPermisos", b =>
                {
                    b.HasOne("Entities.clsModulo", null)
                        .WithMany("permisos")
                        .HasForeignKey("clsModuloid_modulo");
                });

            modelBuilder.Entity("Entities.clsRolPermiso", b =>
                {
                    b.HasOne("Entities.clsPermisos", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoidPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.clsRol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolidRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Entities.clsUsuario", b =>
                {
                    b.HasOne("Entities.clsPersona", "persona")
                        .WithOne()
                        .HasForeignKey("Entities.clsUsuario", "personaId", "personaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Entities.clsTiposAyudas", b =>
                {
                    b.HasOne("Entities.clsUsuario", "responsable")
                        .WithMany()
                        .HasForeignKey("id_responsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.clsUsuario", "usuario_crea")
                        .WithMany()
                        .HasForeignKey("id_usuarioCrea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.clsUsuario", "usuario_ultimaModificacion")
                        .WithMany()
                        .HasForeignKey("id_usuarioUltimaModificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("responsable");

                    b.Navigation("usuario_crea");

                    b.Navigation("usuario_ultimaModificacion");
                });

            modelBuilder.Entity("Entities.clsUsuario", b =>
                {
                    b.HasOne("Entities.clsPersona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId", "PersonaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Entities.clsActivos", b =>
                {
                    b.Navigation("devoluciones");

                    b.Navigation("donacionActivos");
                });

            modelBuilder.Entity("Entities.clsDonacion", b =>
                {
                    b.Navigation("donacionDinero")
                        .IsRequired();

                    b.Navigation("donacionesActivos");
                });

            modelBuilder.Entity("Entities.clsDonante", b =>
                {
                    b.Navigation("donaciones");
                });

            modelBuilder.Entity("Entities.clsModulo", b =>
                {
                    b.Navigation("permisos");
                });

            modelBuilder.Entity("Entities.clsPermisos", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Entities.clsPersona", b =>
                {
                    b.Navigation("donante")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.clsRol", b =>
                {
                    b.Navigation("RolPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
